name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:

  - type: textarea
    id: issue
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context like a stack trace or screenshot about the issue here.

  - type: input
    id: ide
    attributes:
      label: IntelliJ version
      placeholder: 2025.1 Ultimate
    validations:
      required: true

  - type: input
    id: plugin
    attributes:
      label: Plugin version
      placeholder: 2.0.0
    validations:
      required: true
