name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:

  - type: textarea
    id: request
    attributes:
      label: Describe your request
      description: A clear and concise description of what the need or problem is.
    validations:
      required: true
